name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run all tests
        run: mvn -B clean verify -Dspring.profiles.active=it --file pom.xml
      - name: Build docker images and publish in github
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sagar-rout/covid-19-india/covid-19-india
          tag_with_ref: true
      - name: Run docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull docker.pkg.github.com/sagar-rout/covid-19-india/covid-19-india:latest
            docker stop covid-19-india
            docker rm covid-19-india
            docker run -d --network host --name covid-19-india \
            -v $HOME/docker/volumes/covid-19-india/logs:/logs \
            docker.pkg.github.com/sagar-rout/covid-19-india/covid-19-india:latest